---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: eureka-server
  name: eureka-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
        visualize: "true"
    spec:
      containers:
        - name: eureka-server
          image: arthurstrokov/eureka-server:v0.0.0
          imagePullPolicy: IfNotPresent
          env:
            - name: EUREKA-INSTANCE-HOSTNAME
              value: eureka-server
            - name: EUREKA-SERVER-PORT
              value: "8761"
          ports:
            - containerPort: 8761
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-server
spec:
  selector:
    app: eureka-server
  ports:
    - name: eureka-server-port
      port: 8761
      protocol: TCP
      nodePort: 30001
  type: NodePort
