spring:
  main:
    banner-mode: off
  application:
    name: eureka-server
---
server:
  port: ${EUREKA-SERVER-PORT:8761}
eureka:
  instance:
    preferIpAddress: true
    hostname: ${EUREKA-INSTANCE-HOSTNAME:localhost}
    metadata-map:
      metrics.path: /actuator/prometheus
  client:
    register-with-eureka: ${EUREKA-SELF-REGISTRY:false}
    fetch-registry: false
  server:
    enable-self-preservation: false
---
# Actuator
management:
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: [ "*" ]
  info:
    env:
      enabled: true
info:
  application-name: ${spring.application.name}
