spring:
  main:
    banner-mode: off
  application:
    name: eureka-server
---
server:
  port: ${EUREKA-SERVER-PORT:8761}
eureka:
  instance:
    preferIpAddress: true
    hostname: ${EUREKA-INSTANCE-HOSTNAME:localhost}
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false
