---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: {{ .Values.application.name }}
  name: {{ .Values.application.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.application.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.application.name }}
        visualize: "true"
    spec:
      containers:
        - name: {{ .Values.application.name }}
          image: {{ .Values.container.image }}
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: eureka-server-config
          ports:
            - containerPort: 8761
---
apiVersion: v1
kind: Service
metadata:
  labels:
    visualize: "true"
  name: {{ .Values.application.name }}
spec:
  selector:
    app: {{ .Values.application.name }}
  ports:
    - name: eureka-server-port
      protocol: TCP
      port: 8761
      nodePort: 30001
  type: NodePort
